# fly.toml app configuration file generated for openui on 2024-03-15T15:53:15-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'openui'
primary_region = 'sjc'

[http_service]
internal_port = 7878
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "openui_data"
destination = "/root/.openui"

[env]
OPENUI_ENVIRONMENT = "production"
OPENUI_HOST = "https://uiprompt.fly.dev"
GITHUB_CLIENT_ID = "04cc4c3b935a5d14d2f2"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
